### ISSUE TITLE
Deploy to the monitoring namespace and set up CI/CD

### ISSUE THREAD

**Issue by blairdrummond** [blairdrummond/kfp-secret-scanner#2]
At the moment this is live in my namespace and reporting to the daaas-es instance.

However this *should* get deployed to the actual monitoring namespace.

**Comment by justbert** [comment]
Just a quick comment that this should probably not go in the monitoring namespace as that namespace is wholly owned by the Cloud Native Platform and can change without notice. (Fyi, it won't exist in the new AAW).

It may be better to put this in the daaas namespace so that control is maintained at the AAW level.

**Comment by JessicaBarh** [comment]
@blairdrummond do you know which namespace I should be using in ES https://kibana.covid.cloud.statcan.ca/spaces/space_selector if we're not using monitoring?
